name: Build and Deploy Vite App to Azure Web App Slot

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build Vite app
        run: npm run build

      - name: Deploy to Azure Web App Slot
        uses: azure/webapps-deploy@v2
        with:
          app-name: youtubeweb
          slot-name: youtubewebslot  # <-- Your slot name here
          publish-profile: ${{ secrets.AZURE_SLOT_PUBLISH_PROFILE }}
          package: build
